### ISSUE TITLE
Query getEverything with language and sortBy parameter does not work correct

### ISSUE THREAD

**Issue by stormqueen23** [sharmadhiraj/news_api_flutter_package#1]
Hi,

I have installed your package. Thanks for it - simple and easy to use!

I tried to query everything with the parameter 'language'

NewsAPI _newsAPI = NewsAPI('XXXX');
_newsAPI.getEverything(
        query: 'Sommer',
        language: 'de'
      );

This leads to an FormatException.
In the console I see 'de&q=de&apiKey=XXXX'

In your source it seems that sortBy is also wrong:

if (language != null) url = "$language&q=$language";
if (sortBy != null) url = "$sortBy&q=$sortBy";

**Comment by sharmadhiraj** [comment]
Merge PR https://github.com/sharmadhiraj/news_api_flutter_package/pull/2 should fix the issue.
